#!/bin/bash
exec > /dev/null 2>&1
chown -R jenkins. /srv/repo
if [[ -d /var/lib/jenkins/aur-mirror ]]
then
	cd /var/lib/jenkins/aur-mirror
	git reset --hard origin/master
	git clean -fd
	git pull
else
	git clone git://pkgbuild.com/aur-mirror.git /var/lib/jenkins/aur-mirror
fi
sudo abs
