#!/bin/bash

green="$(tput setaf 2)$(tput bold)"
red="$(tput setaf 1)$(tput bold)"
reset="$(tput sgr0)"

/usr/bin/diff -u $@ | \
sed 's/^\([^+-]\)/'$reset'\1/' | \
sed 's/^\(+.*\)$/'$green'\1'$reset'/' | \
sed 's/^\(-.*\)$/'$red'\1'$reset'/'
