version: '2'

services:
    transmission:
        image: justin8/transmission
        network_mode: "service:vpn"
        depends_on:
            - vpn
        volumes:
            - /usr/local/mediaserver/transmission:/config:rw
            - /storage/server-files/downloads:/storage/server-files/downloads:rw
    vpn:
        image: justin8/openvpn-client
        privileged: true
        restart: always
        ports:
            - "9091:9091"
        volumes:
            - /usr/local/mediaserver/openvpn:/config:ro
