#!/bin/bash

cd "$(dirname "$0")"

if [[ $(docker-compose ps | grep Up | wc -l) -eq 2 ]]; then
	echo "A container has exited. Restarting download stack."
	docker-compose down
	docker-compose up -d
fi
