#!/bin/bash

cd "$(dirname "$0")"

if [[ $(docker-compose ps 2>&1 | grep Up | wc -l) -ne 2 ]]; then
	echo "A container has exited. Restarting download stack."
	docker-compose down &>/dev/null
	docker-compose up -d &>/dev/null
fi
