#!/bin/bash

cd "$(dirname "$0")"

expected_process_count=$(grep '^    .[a-zA-Z]*:$' -c docker-compose.yml)
process_count=$(docker-compose ps 2>&1|grep Up -c)

if [[ $process_count -ne $expected_process_count ]]; then
	echo "A container has exited. Restarting download stack."
	mediaserver-restart
fi
