#!/bin/bash

if ! ip route | grep -q 10.1.0.1
then
	# VPN is not connected; kill services and restart VPN. Services will be restarted on next run if it is working.
	warn=0
	systemctl status sabnzb &>/dev/null && warn=1
	systemctl status transmission &>/dev/null && warn=1
	# TODO: Warning won't happen if vpn fails to restart multiple times. Probably ok?
	[[ $warn -eq 1 ]] && echo "VPN has disconnected. Stopping sabnzbd/transmission & restarting openvpn"
	systemctl stop sabnzbd
	systemctl stop transmission
	systemctl restart openvpn@ghostpath.service
else
	# VPN is connected; check services and restart them if necessary
	systemctl status sabnzbd &>/dev/null || (systemctl restart sabnzbd && echo "Restarted sabnzbd")
	systemctl status transmission &>/dev/null || (systemctl restart transmission && echo "Restart transmission")
fi
