version: '2'

services:
    homeassistant:
        image: homeassistant/home-assistant
        network_mode: host
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/lib/hass:/config:rw
