#!/bin/bash

sudo mount -a
ls /mnt/xbmc > /dev/null
while ! mount|grep //abachi/xbmc > /dev/null
do
	echo "/mnt/xbmc does not appear to be mounted yet. Waiting..."
	sleep 1
	ls /mnt/xbmc > /dev/null
	sudo mount -a
done
exec xbmc
